//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Win.rc
//
#define IDC_TaskbarIcon                 4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WIN_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDB_Taskbar                     129
#define IDB_Start                       130
#define IDB_DesktopIcon1                132
#define IDB_DesktopIcon1_Null           133
#define IDB_DesktopIcon2                134
#define IDB_DesktopIcon2_Null           135
#define IDR_WAVE1                       136
#define IDR_TheEnd                      136
#define IDB_StartMenu                   138
#define IDB_TaskbarIcon1                139
#define IDB_TaskbarIcon2                140
#define Desktop                         144
#define IDB_Desktop                     144
#define IDB_Desktop2                    148
#define IDB_Desktop3                    149
#define IDB_Desktop4                    150
#define IDR_WAVE2                       152
#define IDB_Terror_S1                   153
#define IDB_Terror_S2                   154
#define IDB_Terror_S3                   155
#define IDB_Terror_S4                   156
#define IDB_Desktop1                    157
#define IDB_Terror_S5                   158
#define IDB_Terror_S6                   160
#define IDB_Terror1                     162
#define IDB_Terror2                     163
#define IDB_Terror3                     164
#define IDB_Terror4                     165
#define IDB_Terror5                     168
#define IDB_TerrorMusic1                169
#define IDB_TerrorMusic2                170
#define IDB_TerrorMusic3                171
#define IDB_TerrorMusic4                173
#define IDB_TerrorMusic5                174
#define IDB_Picture1                    177
#define IDB_Picture2                    178
#define IDB_Picture3                    179
#define IDB_Terror6                     180
#define IDB_Terror7                     182
#define IDR_Appear                      184
#define IDB_Eyes                        185
#define IDB_DesktopIcon3                188
#define IDB_DesktopIcon3_Null           189
#define IDB_DesktopIcon4                196
#define IDB_DesktopIcon4_Null           197
#define IDB_DesktopIcon5                198
#define IDB_DesktopIcon5_Null           199
#define IDB_TXT1                        200
#define IDB_TXT2                        201
#define IDB_Folder1                     202
#define IDB_Folder2                     203
#define IDB_TaskbarIcon3                205
#define IDB_TaskbarIcon4                206
#define IDR_GIF1                        207
#define IDB_Button1                     208
#define IDB_Button2                     209
#define IDB_Button2_NO                  210
#define IDB_DesktopIcon6                211
#define IDR_GIF2                        212
#define IDB_LoadTXT1                    213
#define IDB_LoadTXT2                    214
#define IDB_LoadTXT3                    215
#define IDB_LoadTXT4                    217
#define IDB_Blue                        218
#define IDR_Appear2                     219
#define IDR_Recycle                     220
#define IDB_DesktopIcon5_Q              221
#define IDB_TaskbarIcon6                222
#define IDR_BackgroundMusic             223
#define IDB_TaskbarIconNull             224
#define IDB_LoadBackground1             225
#define IDB_Black                       226
#define IDB_Windows                     227
#define IDB_User                        228
#define IDR_GIF3                        229
#define IDR_GIF4                        230
#define IDB_Terror8                     231
#define IDB_TerrorMusic6                232
#define IDB_BlurredScreen1              233
#define IDB_BlurredScreen2              234
#define IDB_BlurredScreen3              235
#define IDB_BlurredScreen4              236
#define IDB_BlurredScreen5              237
#define IDB_BlurredScreen6              238
#define IDR_IDB_BlurredScreen           240
#define IDR_WinLoad                     241
#define IDB_StartMenu2                  242
#define IDR_GIF5                        246
#define IDB_Button01                    247
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_Taskbar                     1003
#define IDC_StartBUTTON                 1007
#define IDC_DesktopIcon1                1010
#define IDC_DesktopIcon2                1011
#define IDC_StartMenu                   1012
#define IDC_BUTTON3                     1013
#define IDC_DesktopIcon3                1014
#define IDC_Content                     1015
#define IDC_DesktopIcon4                1016
#define IDC_DesktopIcon5                1017
#define IDC_DesktopIcon6                1018
#define IDC_GifContent                  1020
#define IDC_Close                       1021
#define IDC_Close2                      1022
#define IDC_Loading                     1023
#define IDC_LoadPicture                 1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
